class CategoryList {
  static const List<String> blogCategories = [
    "Technology 💻",
    "Travelling ✈️",
    "Food & Cuisines 🍔",
    "Finance 💰",
    "DIY & Crafts 🛠️",
    "Parenting 👪",
    "Gaming 🎮",
    "Sports ⚽",
    "Education 📚",
    "Anime 🔥",
    "Art & Design 🎨",
    "Music 🎵",
    "Pets 🐶",
    "Science 🔬",
    "Programming 💻",
    "Data Science 📊",
    "Computer Hardware 🖥️",
    "Tradition 🎉",
    "History 📜",
    "Automobiles 🚗",
    "Industry 🏭",
    "Artificial Intelligence 🤖",
    "Art 🖼️",
    "Databases 💾",
    "Nature 🌿",
    "Interior Design 🛋️",
    "Innovations 💡",
    "Facts 🙌",
    "Machines 🛠️",
    "Robotics 🤖",
  ];
}
